module.exports = Object.freeze({
  rpc_url: "https://zksync2-mainnet.zksync.io",
  project_id: "ga-chain",
  dataset_id: "zkSync_era_mainnet",
  tables: {
    transactions: "transactions",
    log_events: "log_events",
    blocks: "blocks",
    block_details: "block_details",
  },
  bq_key: require("./all-user-key.json"),
  bucket_name: "zksync_era_bucket",
  table_schema: {
    transactions: {
      fields: [
        { name: "timestamp", type: "INTEGER" },
        { name: "block_number", type: "INTEGER" },
        { name: "tx_hash", type: "STRING" },
        { name: "type", type: "INTEGER" },
        { name: "block_hash", type: "STRING" },
        { name: "from_address", type: "STRING" },
        { name: "to_address", type: "STRING" },
        { name: "contract_address", type: "STRING" },
        { name: "value", type: "NUMERIC" },
        { name: "data", type: "STRING" },
        { name: "gas_used", type: "NUMERIC" },
        { name: "gas_price", type: "NUMERIC" },
        { name: "nonce", type: "INTEGER" },
        { name: "chain_id", type: "INTEGER" },
        { name: "status", type: "INTEGER" },
        { name: "transaction_index", type: "INTEGER" },
      ],
    },
    blocks: {
      fields: [
        { name: "timestamp", type: "INTEGER" },
        { name: "block_number", type: "INTEGER" },
        { name: "parent_hash", type: "STRING" },
        { name: "block_hash", type: "STRING" },
        { name: "miner", type: "STRING" },
        { name: "total_transactions", type: "INTEGER" },
        { name: "gas_limit", type: "NUMERIC" },
        { name: "gas_used", type: "NUMERIC" },
        { name: "receipt_root", type: "STRING" },
        { name: "sha3_uncles", type: "STRING" },
        { name: "transaction_root", type: "STRING" },
        { name: "log_blooms", type: "STRING" },
      ],
    },
    log_events: {
      fields: [
        { name: "timestamp", type: "INTEGER" },
        { name: "tx_hash", type: "STRING" },
        { name: "block_number", type: "INTEGER" },
        { name: "block_hash", type: "STRING" },
        { name: "transaction_index", type: "INTEGER" },
        { name: "address", type: "STRING" },
        { name: "topics", type: "STRING", mode: "REPEATED" },
        { name: "data", type: "STRING" },
        { name: "log_index", type: "INTEGER" },
      ],
    },
  },
});
